---
name: Uf-Webadmin-Phonebook
version: 0.02
author:
  - University of Florida Web Administration E<lt>webmaster@ufl.eduE<gt>
  - L<http://www.webadmin.ufl.edu/>
abstract: Catalyst based application
license: perl
requires:
  Catalyst: 5.33
  Catalyst::Model::LDAP: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::View::TT: 0
  Class::Accessor: 0
  Locale::Country: 0
  Scalar::Util: 0
  Tree::Simple: 0
  YAML: 0
provides:
  Uf::Webadmin::Phonebook:
    file: lib/Uf/Webadmin/Phonebook.pm
    version: 0.02
  Uf::Webadmin::Phonebook::Constants:
    file: lib/Uf/Webadmin/Phonebook/Constants.pm
  Uf::Webadmin::Phonebook::Controller::People:
    file: lib/Uf/Webadmin/Phonebook/Controller/People.pm
  Uf::Webadmin::Phonebook::Controller::Units:
    file: lib/Uf/Webadmin/Phonebook/Controller/Units.pm
  Uf::Webadmin::Phonebook::Entry:
    file: lib/Uf/Webadmin/Phonebook/Entry.pm
  Uf::Webadmin::Phonebook::Entry::PostalAddress:
    file: lib/Uf/Webadmin/Phonebook/Entry/PostalAddress.pm
  Uf::Webadmin::Phonebook::Entry::PostalAddressCollection:
    file: lib/Uf/Webadmin/Phonebook/Entry/PostalAddressCollection.pm
  Uf::Webadmin::Phonebook::Filter::Abstract:
    file: lib/Uf/Webadmin/Phonebook/Filter/Abstract.pm
  Uf::Webadmin::Phonebook::Filter::Abstract::Operator:
    file: lib/Uf/Webadmin/Phonebook/Filter/Abstract/Operator.pm
  Uf::Webadmin::Phonebook::Filter::Abstract::Predicate:
    file: lib/Uf/Webadmin/Phonebook/Filter/Abstract/Predicate.pm
  Uf::Webadmin::Phonebook::Model::Organizations:
    file: lib/Uf/Webadmin/Phonebook/Model/Organizations.pm
  Uf::Webadmin::Phonebook::Model::People:
    file: lib/Uf/Webadmin/Phonebook/Model/People.pm
  Uf::Webadmin::Phonebook::Utilities:
    file: lib/Uf/Webadmin/Phonebook/Utilities.pm
  Uf::Webadmin::Phonebook::View::TT:
    file: lib/Uf/Webadmin/Phonebook/View/TT.pm
generated_by: Module::Build version 0.25
