# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-LDAP-Filter-Abstract
version:      0.01
version_from: lib/Net/LDAP/Filter/Abstract.pm
installdirs:  site
requires:
    Net::LDAP:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
