---
name: Uf-Webadmin-Phonebook
version: 0.01
author:
  - University of Florida Web Administration E<lt>webmaster@ufl.eduE<gt>
  - L<http://www.webadmin.ufl.edu/>
abstract: Catalyst based application
license: perl
requires:
  Catalyst: 5.10
  Catalyst::Model::LDAP: 0
  Catalyst::View::TT: 0
  Net::LDAP::Filter::Abstract: 0
provides:
  Uf::Webadmin::Phonebook:
    file: lib/Uf/Webadmin/Phonebook.pm
    version: 0.01
  Uf::Webadmin::Phonebook::C::People:
    file: lib/Uf/Webadmin/Phonebook/C/People.pm
  Uf::Webadmin::Phonebook::C::Units:
    file: lib/Uf/Webadmin/Phonebook/C/Units.pm
  Uf::Webadmin::Phonebook::M::Organizations:
    file: lib/Uf/Webadmin/Phonebook/M/Organizations.pm
  Uf::Webadmin::Phonebook::M::People:
    file: lib/Uf/Webadmin/Phonebook/M/People.pm
  Uf::Webadmin::Phonebook::Utilities:
    file: lib/Uf/Webadmin/Phonebook/Utilities.pm
  Uf::Webadmin::Phonebook::V::TT:
    file: lib/Uf/Webadmin/Phonebook/V/TT.pm
generated_by: Module::Build version 0.25
